plugins:
    fixme:
        enabled: true

    nodesecurity:
        enabled: true

    eslint:
        enabled: false

exclude_patterns:
- "**/*.spec.ts"
- "**/node_modules"
- "docs/"
- "build/"
- ".sockTrader"
- ".idea"
