plugins:
    fixme:
        enabled: true

    nodesecurity:
        enabled: true

    eslint:
        enabled: false
        channel: "eslint-6"

exclude_patterns:
- "**/*.spec.ts"
- "**/*.mock.ts"
- "**/jest.config.js"
- "**/node_modules"
- "apps/demo/**/*"
- "docker/"
- "docs/"
- "build/"
- "dist/"
- "tmp/"
- ".github/"
- ".husky/"
