plugins:
    fixme:
        enabled: true

    nodesecurity:
        enabled: true

    eslint:
        enabled: false
        channel: "eslint-6"

exclude_patterns:
- "**/*.spec.ts"
- "**/*.mock.ts"
- "**/node_modules"
- "docs/"
- "build/"
- "dist/"
- "tmp/"
- ".idea"
