version: '3.8'

services:
  postgresql:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - './docker/database:/docker-entrypoint-initdb.d/'
      - './docker/database/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: socktrader
      POSTGRES_PASSWORD: socktrader
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: socktrader
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - './docker/pgadmin/servers.json:/pgadmin4/servers.json'

    ports:
      - '5050:80'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
