name: Build

on:
    push:
        branches: [ master ]

    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 14.x, 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Set NX_HEAD from last successful build
                uses: nrwl/nx-set-shas@v2
                with:
                    main-branch-name: 'master'

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: npm run build:affected -- --base=${{ env.NX_HEAD }}

            -   name: Lint
                run: npm run lint:affected -- --base=${{ env.NX_HEAD }}

            -   name: Unit tests
                run: npm run test:affected -- --base=${{ env.NX_HEAD }}

            -   name: Upload codecoverage report
                uses: codecov/codecov-action@v2
                if: matrix.node-version == '14.x' && github.ref_name == 'master'
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage/coverage-final.json
                    flags: unittests
                    name: codecov-umbrella
                    verbose: true
