name: Build

on:
    push:
        branches:
            - master
            - next
            - beta
            - alpha
            - '*.*.*' # maintenance releases branches

    pull_request:
        types:
            - opened
            - synchronize

env:
    TZ: UTC
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build

        strategy:
            matrix:
                node-version: [ lts/* ]

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: npm ci

#            -   name: Build all packages
#                run: npx nx run-many --target=build --all

            -   name: Build affected
                uses: mansagroup/nrwl-nx-action@v2.1.0
                with:
                    targets: build

#            -   name: Lint all packages
#                run: npx nx run-many --target=lint --all --fix

#            -   name: Lint affected
#                uses: mansagroup/nrwl-nx-action@v2.1.0
#                with:
#                    targets: lint

#            -   name: Unit tests all packages
#                run: npx nx run-many --target=test --verbose --all --parallel --coverage

#            -   name: Unit test affected
#                uses: mansagroup/nrwl-nx-action@v2.1.0
#                with:
#                    targets: test:coverage
#                    parallel: true

#            -   name: Upload codecoverage report
#                uses: codecov/codecov-action@v2
#                with:
#                    files: ./coverage/packages/cli/clover.xml,./coverage/packages/core/clover.xml,./coverage/packages/indicators/clover.xml,./coverage/packages/web/clover.xml
#                    flags: unittests
#                    name: codecov-umbrella
#                    verbose: true

#            -   name: Publish release
#                uses: mansagroup/nrwl-nx-action@v2.1.0
#                with:
#                    targets: release
#                env:
#                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

#                run: npx nx run-many --target=release --verbose --all
            -   name: Build all packages
#                env:
#                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            -   name: Publish release
#                env:
#                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                run: npx semantic-release
