name: Build

on:
  push:
    branches: [ socktrader-v2 ]
  pull_request:
    branches: [ socktrader-v2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --noEmit

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: Upload codecoverage report
        uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '16.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          verbose: true
