name: Build

on:
    push:
        branches: [ master ]

    pull_request:
        branches:
            - '**'

env:
    TZ: UTC

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build

        strategy:
            matrix:
                node-version: [ 14.x, 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: npm ci

            -   name: Build all packages
                run: npx nx run-many --target=build --all

            -   name: Lint all packages
                run: npx nx run-many --target=lint --all --fix

            -   name: Unit tests all packages
                run: npx nx run-many --target=test --verbose --all --parallel

            -   name: Upload codecoverage report
                uses: codecov/codecov-action@v2
                if: matrix.node-version == '14.x' && github.ref_name == 'master'
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage/coverage-final.json
                    flags: unittests
                    name: codecov-umbrella
                    verbose: true
