name: Build

on:
    push:
        branches: [ master ]

    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        permissions:
            contents: 'read'
            actions: 'write'

        strategy:
            matrix:
                node-version: [ 14.x, 16.x ]

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Set NX_HEAD from last successful build
                uses: nrwl/nx-set-shas@v2
                with:
                    main-branch-name: 'master'
                    error-on-no-successful-workflow: false

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: nx affected:build --head=${{ env.NX_HEAD }}

            -   name: Lint
                run: nx affected:lint --head=${{ env.NX_HEAD }}

            -   name: Unit tests
                run: cross-env TZ=UTC nx affected:test --verbose --head=${{ env.NX_HEAD }}

            -   name: Upload codecoverage report
                uses: codecov/codecov-action@v2
                if: matrix.node-version == '14.x' && github.ref_name == 'master'
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage/coverage-final.json
                    flags: unittests
                    name: codecov-umbrella
                    verbose: true

            -   name: Tag main branch if all jobs succeed
                if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
                uses: nrwl/nx-tag-successful-ci-run@v1

